language: python
python:
  - "3.6"
install:
  - pip install -U selenium sauceclient pipenv
  - pipenv install
script:
  - pipenv run behave
addons:
  sauce_connect:
    username: "ben_wolski"
    access_key: "ca8ed953-f7fa-458e-a2f3-2f791cc147a3"
